// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConnectionUpdatePanel: typeof import('./src/components/connection/ConnectionUpdatePanel.vue')['default']
    DkForm: typeof import('./src/components/DkForm.vue')['default']
    DkHeader: typeof import('./src/components/layout/DkHeader.vue')['default']
    DkMain: typeof import('./src/components/layout/DkMain.vue')['default']
    DkMenu: typeof import('./src/components/menu/DkMenu.vue')['default']
    DkMenuItem: typeof import('./src/components/menu/DkMenuItem.vue')['default']
    DkSide: typeof import('./src/components/layout/DkSide.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    MenuLogo: typeof import('./src/components/layout/MenuLogo.vue')['default']
    PageContainer: typeof import('./src/components/layout/PageContainer.vue')['default']
    RedisCell: typeof import('./src/components/redis/RedisCell.vue')['default']
    RedisDataUpdatePanel: typeof import('./src/components/redis/RedisDataUpdatePanel.vue')['default']
    RedisDb: typeof import('./src/components/redis/RedisDb.vue')['default']
    RedisHashConfirmTips: typeof import('./src/components/redis/update/RedisHashConfirmTips.vue')['default']
    RedisHashUpdate: typeof import('./src/components/redis/update/RedisHashUpdate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserHeader: typeof import('./src/components/layout/UserHeader.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
